---
title: "lab_1"
author: "Siya Qiu"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
```

Read data
```{r, message = FALSE}
us_landings <- read_csv(here::here("data", "noaa_fisheries.csv")) %>% 
  janitor::clean_names()
```

Now make a tidy version of the df 
```{r}
landings_tidy <- us_landings %>% 
  mutate(state = str_to_lower(state),
         afs_name = str_to_lower(afs_name)) %>% 
  mutate(dollars_usd = parse_number(dollars_usd)) # parse_number: 移除数字前后的字母符号
```

Let's get some info for salmon 
```{r}
salmon_landings <- landings_tidy %>% 
  mutate(afs_clean = str_remove(afs_name, pattern = "aggregate")) %>% # 移除aggregate的字样
  filter(str_detect(afs_clean, pattern = "salmon")) %>% 
  separate(afs_clean, into = c("group", "species"), sep = ",") #  同一个cell里有好几个词，用逗号隔开的，可以这样分组
```

Find some group summary data: 
Find annual total us landing and dolar value by summing across all stagefor each type of salmon using group_by = summarize 
```{r}
salmon_summary <- salmon_landings %>% 
  group_by(year, species) %>% 
  summarize(
    tot_landings = sum(landings_pounds),
    tot_value = sum(dollars_usd))
```

Make a graph
```{r}
salmon_landings_graph <- ggplot(data = salmon_summary, aes(x = year, y = tot_landings)) + 
  geom_line(aes(color = species)) + 
  theme_minimal()
  
salmon_landings_graph
```

Now we will export our graph with ggsave
```{r}
ggsave(plot = salmon_landings_graph,
       here("figures", "us_salmon_sq.png"),
       height = 5, 
       width = 8)
```

Make a nice kable table 
```{r}
salmon_first_5 <- salmon_summary %>% 
  head(5)
```

```{r}
kable(salmon_first_5) %>% 
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE)
```

